In [ ]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# go to your project directory
%cd /content/drive/MyDrive

#Data

In [ ]:
df = pd.read_csv("tvseries_data.csv")
df.head(5)

,title,description,genres
0,You,"A dangerously charming, intensely obsessive yo...","['Crime', 'Drama', 'Romance']"
1,Outer Banks,"On an island of haves and have-nots, teen John...","['Action', 'Crime', 'Drama']"
2,That '90s Show,"Now it's 1995, Leia Forman is visiting her gra...","['Comedy', 'Drama', 'Romance']"
3,Grey's Anatomy,A drama centered on the personal and professio...,"['Drama', 'Romance']"
4,House of the Dragon,An internal succession war within House Targar...,"['Action', 'Adventure', 'Drama']"

In [ ]:
df2 = pd.read_csv("movies_data.csv")
df2.head(5)

,title,description,genres
0,Black Panther: Wakanda Forever,The people of Wakanda fight to protect their h...,"['Action', 'Adventure', 'Drama']"
1,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,"['Action', 'Adventure', 'Fantasy']"
2,Plane,A pilot finds himself caught in a war zone aft...,"['Action', 'Adventure', 'Thriller']"
3,Everything Everywhere All at Once,A middle-aged Chinese immigrant is swept up in...,"['Action', 'Adventure', 'Comedy']"
4,Fast X,Dom Toretto and his family are targeted by the...,"['Action', 'Crime', 'Mystery']"

In [ ]:
df3 = df.append(df2, ignore_index=True)
df3.head(5)

,title,description,genres
0,You,"A dangerously charming, intensely obsessive yo...","['Crime', 'Drama', 'Romance']"
1,Outer Banks,"On an island of haves and have-nots, teen John...","['Action', 'Crime', 'Drama']"
2,That '90s Show,"Now it's 1995, Leia Forman is visiting her gra...","['Comedy', 'Drama', 'Romance']"
3,Grey's Anatomy,A drama centered on the personal and professio...,"['Drama', 'Romance']"
4,House of the Dragon,An internal succession war within House Targar...,"['Action', 'Adventure', 'Drama']"

In [ ]:
df.shape

(43496, 3)

In [ ]:
df2.shape

(14563, 3)

In [ ]:
df3.shape

(58059, 3)

In [ ]:
genres_list = df3.genres.to_list()

genre_count = {}
for genres in genres_list:
  try:
    genre_list = eval(genres)
    for genre in genre_list:
      if genre in genre_count.keys():
        genre_count[genre] += 1
      else:
        genre_count[genre] = 1
  except:
    pass
  

print(f"Number of Genres: {len(genre_count)}")
print(genre_count)

Number of Genres: 28
{'Crime': 14497, 'Drama': 28150, 'Romance': 8553, 'Action': 26440, 'Comedy': 12833, 'Adventure': 10885, 'Fantasy': 6937, 'Sport': 362, 'Horror': 2774, 'Mystery': 6060, 'History': 1402, 'Biography': 561, 'Family': 2377, 'Animation': 8202, 'Musical': 222, 'Music': 325, 'Short': 696, 'Game-Show': 173, 'Reality-TV': 474, 'Sci-Fi': 2276, 'War': 472, 'Thriller': 4520, 'Western': 229, 'Documentary': 966, 'Talk-Show': 41, 'News': 34, 'Film-Noir': 9, 'Adult': 1}

In [ ]:
df3.isna().sum()

title          0
description    1
genres         0
dtype: int64

In [ ]:
df3 = df3.dropna().reset_index(drop=True)

In [ ]:
df3 = df3.drop_duplicates(subset=["title"], keep=False)
print(len(df3))

28956

In [ ]:
list = ["Plot kept under wraps.", "Plot under wraps.", "Plot unknown.", "Add a Plot", "The plot is unknown at this time.", "Plot details kept under wraps."]
df3 = df3[df3.description.isin(list) == False]
print(len(df3))

25326

In [ ]:
df3.to_csv("movies_and_tvseries.csv", index=False)